version: '3'

services:
  webserver:
    container_name: achats_webserver
    image: php:8-apache
    volumes:
      - ./html:/var/www/html
    ports:
      - "8000:80"
    restart: always
  
  api:
    container_name: achats_api
    build: .
    volumes:
      - ./api:/code/app
    ports:
      - "8001:80"
    restart: always
